### ISSUE TITLE
Laravel CSP (content security policy) frontegg ui integrate issue

### ISSUE THREAD

**Issue by komelabbbas** [frontegg/frontegg-vue#278]
https://github.com/spatie/laravel-csp

I Need help,

After i added the laravel csp the front egg vue login page not working.

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://fonts.googleapis.com/ 'nonce-loop' 'unsafe-inline' nonce-loop". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-loop' 'unsafe-inline' nonce-loop". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

Please help how to fix this issue ?

```
// frontegg
$this->addDirective(Directive::SCRIPT, 'https://assets.frontegg.com');
$this->addDirective(Directive::CONNECT, 'https://frontegg.com');
$this->addDirective(Directive::CONNECT, 'https://app-g6y1wrdhmmrt.frontegg.com');
$this->addDirective(Directive::IMG, 'https://fronteggprodeustorage.blob.core.windows.net');
$this->addDirective(Directive::STYLE, 'unsafe-inline');
```

### **BEFORE**:
![Screenshot 2023-04-11 at 11 05 52 AM](https://user-images.githubusercontent.com/51354419/231066100-2617c8ee-1ed1-4c30-a0ff-6f1c2c7efdb5.png)

### **AFTER**:
![uGCPz](https://user-images.githubusercontent.com/51354419/231066039-eaf216fa-a316-430c-be89-2dc65fa70b3c.png)

**Comment by yuvalotem1** [comment]
Hey @komelabbbas, With CSP, you can limit which data sources are allowed by a web application, by defining the appropriate CSP directive in the HTTP response header. 
In this case you need to add Frontegg assets to your allowed data sources - 
```
https://assets.frontegg.com
https://app-g6y1wrdhmmrt.frontegg.com 
https://app-g6y1wrdhmmrt.frontegg.com 
https://fronteggprodeustorage.blob.core.windows.net
```
