### ISSUE TITLE
[BUG] Incorrect type definition for `useFeatureEntitlements`

### ISSUE THREAD

**Issue by hognevevle** [frontegg/frontegg-vue#393]
`const foo = useFeatureEntitlements("bar");`

`foo` is now, according to Typescript, of type `Entitlement`. 
During runtime, however, it is in fact a `Ref<Entitlement>`. 

This causes problems when you're not directly using `foo` in the component html, but instead using it elsewhere in the `script` part.

You are then forced to do something like this:

`(foo as unknown as Ref<typeof foo>).value.isEntitled`
(alternatively `unref(foo).isEntitled`)

Proof:
```
  console.log("checking entitlement");
  console.log(foo.isEntitled);
  console.log((foo as unknown as Ref<typeof foo>).value.isEntitled);
```
Outputs:
![CleanShot 2024-01-12 at 12 42 56](https://github.com/frontegg/frontegg-vue/assets/2721188/fe37eccd-a3fa-4944-9334-0946fd69a00e)

In this case, the user is indeed entitled, so `true` is the correct output.

Similar to https://github.com/frontegg/frontegg-vue/issues/349

**Comment by doregg** [comment]
@hognevevle Thanks for reporting the issue. We will take a look and update.

**Comment by hognevevle** [comment]
Thanks @doregg , but it seems the typings disappeared after this change (now returning `any` instead). 🤔 

![CleanShot 2024-01-15 at 11 56 58](https://github.com/frontegg/frontegg-vue/assets/2721188/1c2ce83e-8087-42d9-b43f-0ff0e01f4d5b)
![CleanShot 2024-01-15 at 11 56 14](https://github.com/frontegg/frontegg-vue/assets/2721188/a531f4b7-abcc-42c4-8c9d-2bc498b6be7a)

npmjs.com confirms the same:

![CleanShot 2024-01-15 at 11 58 12](https://github.com/frontegg/frontegg-vue/assets/2721188/d92e7237-61f2-43fe-9197-550ca9ec9af6)

**Comment by hognevevle** [comment]
@doregg Can you please reopen this?
