### ISSUE TITLE
[BUG] Incorrect `authState` after logging in as another user when using `enableSessionPerTenant`

### ISSUE THREAD

**Issue by hognevevle** [frontegg/frontegg-vue#409]
**Describe the bug**
When `authOptions.enableSessionPerTenant` is enabled, the stored value in SessionStorage (`FRONTEGG_SEPARATE_TABS_BY_TENANT`) does not get cleared when signing out.

If you then sign in as another user, `authState.user.tenantId` will then still have the value from the previous user, even if the new user does not have access to that tenant.

In my case, we're using embedded login, so I'm not sure if the issue exists both for embedded and hosted.

**To Reproduce**
- Set `authOptions.enableSessionPerTenant` to `true`
- Print `authState.user.tenantId` somewhere in the app
- Sign in as some user A, and notice the tenantId printed
- Sign out
- Sign in as another user B that does not belong to the tenant of the previous user
- `authState.user.tenantId` will still have the value from user A

**Expected behavior**
The tenant id should be cleared when logging out.

**Comment by TomerFrontegg** [comment]
fixed in **v3.0.21**
